app = "domaintobiz-worker-misty-sun-2826"
primary_region = "atl"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  worker = "python poller.py"

# Background worker configuration
[http_service]
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1 